---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-cert-corp
  namespace: cilium-gateway
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICLzCCAdWgAwIBAgIRAIFXnsaa/GuH2ZK55M2eO+cwCgYIKoZIzj0EAwIwMjEP
    MA0GA1UEChMGazhzIENBMR8wHQYDVQQDExZrOHMgQ0EgSW50ZXJtZWRpYXRlIENB
    MB4XDTI1MTAxNjEyMTkzNFoXDTM1MTAxNDEyMjAzNFowGDEWMBQGA1UEAwwNKi5v
    a2J0c3AuY29ycDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNVkGrr9Cs7/B5zv
    XfqL01iKNnq9bsDz+WumgmCagPGpuCevfUpXd3EC+bga6jkzZBGTb34j+cW/9Gs+
    QDQIGA+jgeUwgeIwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjAdBgNVHQ4EFgQU56PQ/LtXKteIBQTAquuKSYbzfiQwHwYDVR0j
    BBgwFoAUrNN0EfWNwf2JUdVxOwbFGYBfqkYwJQYDVR0RBB4wHIINKi5va2J0c3Au
    Y29ycIILb2tidHNwLmNvcnAwSgYMKwYBBAGCpGTGKEABBDowOAIBAQQGbWFudWFs
    BCtOT0NCekVoUHRBM0hiM0RwVi1ydkJYeFBoM2Fjb2Y5VVFQeGlIX1RUNjhvMAoG
    CCqGSM49BAMCA0gAMEUCIQD4/5YFN1uqYBy2/EjB45dYa7W/z/ZOVkIrEswGlizi
    8QIgRZeGy+cfuA0qPfnwC0C4lumjxCBz7oGxJWqVKv4qZco=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIC5DCCAcygAwIBAgIQENfDZ275e7KA87qXmn2k0jANBgkqhkiG9w0BAQsFADCB
    jDELMAkGA1UEBhMCQlkxEzARBgNVBAgTCkJlbGFydXNpYW4xDjAMBgNVBAcTBU1p
    bnNrMQ4wDAYDVQQKEwVJTkZSQTEMMAoGA1UECxMDT0lUMRswGQYDVQQDExJLOHND
    QS5va2J0c3AubG9jYWwxHTAbBgkqhkiG9w0BCQEWDm9pdEBva2J0c3AuY29tMB4X
    DTI1MDMzMTE5MTMxMloXDTM1MDMyOTE5MTMxMlowMjEPMA0GA1UEChMGazhzIENB
    MR8wHQYDVQQDExZrOHMgQ0EgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEVRwODyIoKIs9PG49z1VXHpxD/wQPeXDhRm0Xs0cgPkTEoFhY
    vIXbo3rw1WA3XMGvxbuyv6e1KGA87iz4p2OmiqNmMGQwDgYDVR0PAQH/BAQDAgEG
    MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFKzTdBH1jcH9iVHVcTsGxRmA
    X6pGMB8GA1UdIwQYMBaAFL1V/CAwB0cwV1Uj+XpQSNRa/FMFMA0GCSqGSIb3DQEB
    CwUAA4IBAQAs995tTLM02midwwNJU55RcflQ2umDdKHxjnRAf7W8OzSjmexazbpC
    z2FShaxN+pYt+53v+Mf1ZzKY6bdTZb0y6/7DuLraYvbsStDaWLgeSwBzAmV6iVrS
    BNv/+EmQ5xgx2IovIlvB2meYXOZa3e5e5hgQlqe4xTieMH+0ChdaUBU7YGgmAuTe
    EvSKaTc1Aztk+DqCPFXMj+XxDRYHj7xTBqnsaKWffI+2F0ncuPDvM61VWupqB+I0
    l4CbdVGaHsu93+U6DetBFQA3u7GIXcBVx/wIy9wxuF8ys4ka/D++Al57O0RjPHm/
    0OI7FjuLqd7oAhRTIpNGJ80qEPh3mh6P
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFmjCCBIKgAwIBAgITYQAAAAUOw3naxQsWhQAAAAAABTANBgkqhkiG9w0BAQsF
    ADA6MTgwNgYDVQQDEy9JbmZyYS5jb3JwIENsYXNzIDEgUm9vdCBDZXJ0aWZpY2F0
    aW9uIEF1dGhvcml0eTAeFw0yNTAzMzExNDMyMDhaFw0zMDAzMzExNDQyMDhaMIGM
    MQswCQYDVQQGEwJCWTETMBEGA1UECBMKQmVsYXJ1c2lhbjEOMAwGA1UEBxMFTWlu
    c2sxDjAMBgNVBAoTBUlORlJBMQwwCgYDVQQLEwNPSVQxGzAZBgNVBAMTEks4c0NB
    Lm9rYnRzcC5sb2NhbDEdMBsGCSqGSIb3DQEJARYOb2l0QG9rYnRzcC5jb20wggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDqUKASW9khaqt2CfdKzr1EZ4Mf
    cnSKUmpU57Nh/vaMYg9m0rj/k2OPRL96GzqrcNEq/CqwKmlN5HXVBwPU8D7xq2Mv
    +iswjFn3fB9rT4hDf0XmCaFGD4WiWLV1MLC/BvedeL3lONoWe9bPEJuj0RK/LnWA
    4nUl24B0aUfi96VYXQH+lu/ic61TbjZJ4RlhEvVoOBgfrfwJ2+1cnoFfq9C5dN81
    8LmQvAjN7MFKefPOEwaF3aqDbcBU+rP7WHlv/8hQs7l18/sCU6ISJ6dAd1itaByK
    hsU6Kp3eM/9GbFsZA7nHXxe+YVlHnsccflImMmedPDeOJsbc/LEE35PglROVAgMB
    AAGjggJEMIICQDAdBgNVHQ4EFgQUvVX8IDAHRzBXVSP5elBI1Fr8UwUwHwYDVR0j
    BBgwFoAUn9vO2Z00whB7tjFUQFDAKHkJyk0wgdIGA1UdHwSByjCBxzCBxKCBwaCB
    voZeaHR0cDovL3BraS5va2J0c3AubG9jYWwvQ2VydERhdGEvSW5mcmEuY29ycCUy
    MENsYXNzJTIwMSUyMFJvb3QlMjBDZXJ0aWZpY2F0aW9uJTIwQXV0aG9yaXR5LmNy
    bIZcaHR0cDovL3BraS5pbmZyYS5jb3JwL0NlcnREYXRhL0luZnJhLmNvcnAlMjBD
    bGFzcyUyMDElMjBSb290JTIwQ2VydGlmaWNhdGlvbiUyMEF1dGhvcml0eS5jcmww
    ge8GCCsGAQUFBwEBBIHiMIHfMHQGCCsGAQUFBzAChmhodHRwOi8vcGtpLm9rYnRz
    cC5sb2NhbC9DZXJ0RGF0YS9Sb290Q0EtMDFfSW5mcmEuY29ycCUyMENsYXNzJTIw
    MSUyMFJvb3QlMjBDZXJ0aWZpY2F0aW9uJTIwQXV0aG9yaXR5LmNydDBnBggrBgEF
    BQcwAoZbaHR0cDovcGtpLmluZnJhLmNvcnAvQ2VydERhdGEvUm9vdENBLTAxX0lu
    ZnJhLmNvcnAgQ2xhc3MgMSBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5LmNy
    dDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAPBgNVHRMBAf8EBTADAQH/MAsG
    A1UdDwQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEAZLMaHDm2njW3I+eWX8glirtr
    BwdNay4ryraMA7WpznuWQbpTzefVgCPL3hcF4nZfGJ3s/dyTfNfeYkoA83atzuzG
    axTanxe405AvnJ5k8ZnAuNNk5LcnAjCRMktPpm23rON0AteGsp0z/sb5mt/B/W8O
    SEwTqMeqtNGK4ERwqWYaiX8nVNL5VfhCxKjl8i0izM5wG9VfpGEv8tJw43o6dxyc
    UkZNj82JOtWfsXtupxOB24Of1ZZ4FrAeD0Z+yy0glzvEIJkkrBv2UKdC/F1qg8BN
    YCkBiizmWNQifrLOph6GDIR0qIYwdSSfFnzrVrCyf93FkF3Hz3RPJmduqQN3Hw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgITEwAAAAfYBWHRqjIGSQAAAAAABzANBgkqhkiG9w0BAQ0F
    ADAYMRYwFAYDVQQDEw1Sb290Q0EtT0tCVFNQMB4XDTIzMDUxMTIwMTQxMVoXDTI2
    MDUxMTIwMjQxMVowUjESMBAGCgmSJomT8ixkARkWAmJ5MRYwFAYKCZImiZPyLGQB
    GRYGb2tidHNwMSQwIgYDVQQDExtva2J0c3AtU1JWLVNVQkNBLTAxLUNBLTIwMjMw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKKggRtANu6NGp2RL1EYFz
    PEd+8T4dNbbwO3smJ5DZJT+CtNkNdq+N1BLhBJLAQYhueMYb84tTRsyUVarXRLuk
    7HrgwfbQH0aGrlbdU+ylCCYTXkcKQDzY2q0dORO5VsODI5qY5sVDnfxl+hZHvaFw
    4BqBU27z7iRFZT9eTb+mOYDLoXOP5jitqICwkjxSAg88c5orVsQW7+7/SolRu+9T
    mt1Io1aTT6MpzyEZlRkjEKwu9dHrwewsZvg9Ery1nq8lF2Q+gkJbEsgQhTMkIxuZ
    PN74IioXUP8R69H9rgPsuOn4s8c0IxOXgNrgaGow7mWelSuYfMmZabKDrWNMOptp
    AgMBAAGjggHNMIIByTAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUflZ69UDt
    N9Eays4exhDZ2HSwguQwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0P
    BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAUFzqKJ3Ym3Hnt83El
    SEuOlRXhJtYwfwYDVR0fBHgwdjB0oHKgcIY3aHR0cDovL3Nydi1zdWJjYS0wMS5v
    a2J0c3AuY29ycC9DZXJ0cy9Sb290Q0EtT0tCVFNQLmNybIY1aHR0cDovL3Nydi1z
    dWJjYS0wMS5va2J0c3AuYnkvQ2VydHMvUm9vdENBLU9LQlRTUC5jcmwwgboGCCsG
    AQUFBwEBBIGtMIGqMFQGCCsGAQUFBzAChkhodHRwOi8vc3J2LXN1YmNhLTAxLm9r
    YnRzcC5jb3JwL0NlcnRzQUlBL3Nydi1yb290Y2EtMDFfUm9vdENBLU9LQlRTUC5j
    cnQwUgYIKwYBBQUHMAKGRmh0dHA6Ly9zcnYtc3ViY2EtMDEub2tidHNwLmJ5L0Nl
    cnRzQUlBL3Nydi1yb290Y2EtMDFfUm9vdENBLU9LQlRTUC5jcnQwDQYJKoZIhvcN
    AQENBQADggIBAJEp2DWhXkpCvHLZaEveXSP2wROghoiqkWO1drlDDZfX19b2oHdH
    vYmOkYust9o47qilQLG962Amk25xtpHN8RT8X9EUdFTtgXmDPsYK6heW5ys/CZRC
    cw1UvwZayI9yOo/h2vwJIURf5thwS/5k6gqJLmHkxAIl325juFCKhueOiQS/VlxZ
    a06lpEnDKXqxpZ1oySvmZV53mcx27dEisOyE7S4EEL/4Th6FXQKzni5ojUwJX6g/
    ix9Ox6Fa4FwbFqrV2IHbuYOudBNnZCuDJEQBSMcznx4eepTb/a/e1Gno6zV31Qpg
    3b6537XeMLmh9vOFo3Z88ignjQME7TfnykA1f0r4pWuOzsOtoad42ntoct1XNSd5
    Q1bzIpUjuA0BgIbpoTh4zHnJzfBGIxnpQKp4B26SSHPRh/iw5whviXsPBFDXcnTK
    6nt0w7l2Tsy6cxIVo+ZUlSJ/e4ey9j30+Lq6nexPn5P8eGTGzuh98it2d5OPOUv4
    xycQhD4bBVk8Ls5gCdgj2atSyHR4wnveCfIR1w8G4ooDhbfmhiL7frpZebJe6uRN
    6I2Ce6LlLB24uRJrIZ+RZR0f00WPYpApY+Q+NOShd9MZMikTWusT8NriiLvzeA0+
    CKs7HjA5q0pWQcxwEvA5wvWuU0WOt4tlGAfuAclJF29x3qDN2EBQAM+b
    -----END CERTIFICATE-----
  tls.key: |
    {{ talos_shared_gateway_corp_key | indent(4) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-cert-com
  namespace: cilium-gateway
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICLzCCAdWgAwIBAgIRAIFXnsaa/GuH2ZK55M2eO+cwCgYIKoZIzj0EAwIwMjEP
    MA0GA1UEChMGazhzIENBMR8wHQYDVQQDExZrOHMgQ0EgSW50ZXJtZWRpYXRlIENB
    MB4XDTI1MTAxNjEyMTkzNFoXDTM1MTAxNDEyMjAzNFowGDEWMBQGA1UEAwwNKi5v
    a2J0c3AuY29ycDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNVkGrr9Cs7/B5zv
    XfqL01iKNnq9bsDz+WumgmCagPGpuCevfUpXd3EC+bga6jkzZBGTb34j+cW/9Gs+
    QDQIGA+jgeUwgeIwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjAdBgNVHQ4EFgQU56PQ/LtXKteIBQTAquuKSYbzfiQwHwYDVR0j
    BBgwFoAUrNN0EfWNwf2JUdVxOwbFGYBfqkYwJQYDVR0RBB4wHIINKi5va2J0c3Au
    Y29ycIILb2tidHNwLmNvcnAwSgYMKwYBBAGCpGTGKEABBDowOAIBAQQGbWFudWFs
    BCtOT0NCekVoUHRBM0hiM0RwVi1ydkJYeFBoM2Fjb2Y5VVFQeGlIX1RUNjhvMAoG
    CCqGSM49BAMCA0gAMEUCIQD4/5YFN1uqYBy2/EjB45dYa7W/z/ZOVkIrEswGlizi
    8QIgRZeGy+cfuA0qPfnwC0C4lumjxCBz7oGxJWqVKv4qZco=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIC5DCCAcygAwIBAgIQENfDZ275e7KA87qXmn2k0jANBgkqhkiG9w0BAQsFADCB
    jDELMAkGA1UEBhMCQlkxEzARBgNVBAgTCkJlbGFydXNpYW4xDjAMBgNVBAcTBU1p
    bnNrMQ4wDAYDVQQKEwVJTkZSQTEMMAoGA1UECxMDT0lUMRswGQYDVQQDExJLOHND
    QS5va2J0c3AubG9jYWwxHTAbBgkqhkiG9w0BCQEWDm9pdEBva2J0c3AuY29tMB4X
    DTI1MDMzMTE5MTMxMloXDTM1MDMyOTE5MTMxMlowMjEPMA0GA1UEChMGazhzIENB
    MR8wHQYDVQQDExZrOHMgQ0EgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEVRwODyIoKIs9PG49z1VXHpxD/wQPeXDhRm0Xs0cgPkTEoFhY
    vIXbo3rw1WA3XMGvxbuyv6e1KGA87iz4p2OmiqNmMGQwDgYDVR0PAQH/BAQDAgEG
    MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFKzTdBH1jcH9iVHVcTsGxRmA
    X6pGMB8GA1UdIwQYMBaAFL1V/CAwB0cwV1Uj+XpQSNRa/FMFMA0GCSqGSIb3DQEB
    CwUAA4IBAQAs995tTLM02midwwNJU55RcflQ2umDdKHxjnRAf7W8OzSjmexazbpC
    z2FShaxN+pYt+53v+Mf1ZzKY6bdTZb0y6/7DuLraYvbsStDaWLgeSwBzAmV6iVrS
    BNv/+EmQ5xgx2IovIlvB2meYXOZa3e5e5hgQlqe4xTieMH+0ChdaUBU7YGgmAuTe
    EvSKaTc1Aztk+DqCPFXMj+XxDRYHj7xTBqnsaKWffI+2F0ncuPDvM61VWupqB+I0
    l4CbdVGaHsu93+U6DetBFQA3u7GIXcBVx/wIy9wxuF8ys4ka/D++Al57O0RjPHm/
    0OI7FjuLqd7oAhRTIpNGJ80qEPh3mh6P
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFmjCCBIKgAwIBAgITYQAAAAUOw3naxQsWhQAAAAAABTANBgkqhkiG9w0BAQsF
    ADA6MTgwNgYDVQQDEy9JbmZyYS5jb3JwIENsYXNzIDEgUm9vdCBDZXJ0aWZpY2F0
    aW9uIEF1dGhvcml0eTAeFw0yNTAzMzExNDMyMDhaFw0zMDAzMzExNDQyMDhaMIGM
    MQswCQYDVQQGEwJCWTETMBEGA1UECBMKQmVsYXJ1c2lhbjEOMAwGA1UEBxMFTWlu
    c2sxDjAMBgNVBAoTBUlORlJBMQwwCgYDVQQLEwNPSVQxGzAZBgNVBAMTEks4c0NB
    Lm9rYnRzcC5sb2NhbDEdMBsGCSqGSIb3DQEJARYOb2l0QG9rYnRzcC5jb20wggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDqUKASW9khaqt2CfdKzr1EZ4Mf
    cnSKUmpU57Nh/vaMYg9m0rj/k2OPRL96GzqrcNEq/CqwKmlN5HXVBwPU8D7xq2Mv
    +iswjFn3fB9rT4hDf0XmCaFGD4WiWLV1MLC/BvedeL3lONoWe9bPEJuj0RK/LnWA
    4nUl24B0aUfi96VYXQH+lu/ic61TbjZJ4RlhEvVoOBgfrfwJ2+1cnoFfq9C5dN81
    8LmQvAjN7MFKefPOEwaF3aqDbcBU+rP7WHlv/8hQs7l18/sCU6ISJ6dAd1itaByK
    hsU6Kp3eM/9GbFsZA7nHXxe+YVlHnsccflImMmedPDeOJsbc/LEE35PglROVAgMB
    AAGjggJEMIICQDAdBgNVHQ4EFgQUvVX8IDAHRzBXVSP5elBI1Fr8UwUwHwYDVR0j
    BBgwFoAUn9vO2Z00whB7tjFUQFDAKHkJyk0wgdIGA1UdHwSByjCBxzCBxKCBwaCB
    voZeaHR0cDovL3BraS5va2J0c3AubG9jYWwvQ2VydERhdGEvSW5mcmEuY29ycCUy
    MENsYXNzJTIwMSUyMFJvb3QlMjBDZXJ0aWZpY2F0aW9uJTIwQXV0aG9yaXR5LmNy
    bIZcaHR0cDovL3BraS5pbmZyYS5jb3JwL0NlcnREYXRhL0luZnJhLmNvcnAlMjBD
    bGFzcyUyMDElMjBSb290JTIwQ2VydGlmaWNhdGlvbiUyMEF1dGhvcml0eS5jcmww
    ge8GCCsGAQUFBwEBBIHiMIHfMHQGCCsGAQUFBzAChmhodHRwOi8vcGtpLm9rYnRz
    cC5sb2NhbC9DZXJ0RGF0YS9Sb290Q0EtMDFfSW5mcmEuY29ycCUyMENsYXNzJTIw
    MSUyMFJvb3QlMjBDZXJ0aWZpY2F0aW9uJTIwQXV0aG9yaXR5LmNydDBnBggrBgEF
    BQcwAoZbaHR0cDovcGtpLmluZnJhLmNvcnAvQ2VydERhdGEvUm9vdENBLTAxX0lu
    ZnJhLmNvcnAgQ2xhc3MgMSBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5LmNy
    dDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAPBgNVHRMBAf8EBTADAQH/MAsG
    A1UdDwQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEAZLMaHDm2njW3I+eWX8glirtr
    BwdNay4ryraMA7WpznuWQbpTzefVgCPL3hcF4nZfGJ3s/dyTfNfeYkoA83atzuzG
    axTanxe405AvnJ5k8ZnAuNNk5LcnAjCRMktPpm23rON0AteGsp0z/sb5mt/B/W8O
    SEwTqMeqtNGK4ERwqWYaiX8nVNL5VfhCxKjl8i0izM5wG9VfpGEv8tJw43o6dxyc
    UkZNj82JOtWfsXtupxOB24Of1ZZ4FrAeD0Z+yy0glzvEIJkkrBv2UKdC/F1qg8BN
    YCkBiizmWNQifrLOph6GDIR0qIYwdSSfFnzrVrCyf93FkF3Hz3RPJmduqQN3Hw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgITEwAAAAfYBWHRqjIGSQAAAAAABzANBgkqhkiG9w0BAQ0F
    ADAYMRYwFAYDVQQDEw1Sb290Q0EtT0tCVFNQMB4XDTIzMDUxMTIwMTQxMVoXDTI2
    MDUxMTIwMjQxMVowUjESMBAGCgmSJomT8ixkARkWAmJ5MRYwFAYKCZImiZPyLGQB
    GRYGb2tidHNwMSQwIgYDVQQDExtva2J0c3AtU1JWLVNVQkNBLTAxLUNBLTIwMjMw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKKggRtANu6NGp2RL1EYFz
    PEd+8T4dNbbwO3smJ5DZJT+CtNkNdq+N1BLhBJLAQYhueMYb84tTRsyUVarXRLuk
    7HrgwfbQH0aGrlbdU+ylCCYTXkcKQDzY2q0dORO5VsODI5qY5sVDnfxl+hZHvaFw
    4BqBU27z7iRFZT9eTb+mOYDLoXOP5jitqICwkjxSAg88c5orVsQW7+7/SolRu+9T
    mt1Io1aTT6MpzyEZlRkjEKwu9dHrwewsZvg9Ery1nq8lF2Q+gkJbEsgQhTMkIxuZ
    PN74IioXUP8R69H9rgPsuOn4s8c0IxOXgNrgaGow7mWelSuYfMmZabKDrWNMOptp
    AgMBAAGjggHNMIIByTAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUflZ69UDt
    N9Eays4exhDZ2HSwguQwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0P
    BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAUFzqKJ3Ym3Hnt83El
    SEuOlRXhJtYwfwYDVR0fBHgwdjB0oHKgcIY3aHR0cDovL3Nydi1zdWJjYS0wMS5v
    a2J0c3AuY29ycC9DZXJ0cy9Sb290Q0EtT0tCVFNQLmNybIY1aHR0cDovL3Nydi1z
    dWJjYS0wMS5va2J0c3AuYnkvQ2VydHMvUm9vdENBLU9LQlRTUC5jcmwwgboGCCsG
    AQUFBwEBBIGtMIGqMFQGCCsGAQUFBzAChkhodHRwOi8vc3J2LXN1YmNhLTAxLm9r
    YnRzcC5jb3JwL0NlcnRzQUlBL3Nydi1yb290Y2EtMDFfUm9vdENBLU9LQlRTUC5j
    cnQwUgYIKwYBBQUHMAKGRmh0dHA6Ly9zcnYtc3ViY2EtMDEub2tidHNwLmJ5L0Nl
    cnRzQUlBL3Nydi1yb290Y2EtMDFfUm9vdENBLU9LQlRTUC5jcnQwDQYJKoZIhvcN
    AQENBQADggIBAJEp2DWhXkpCvHLZaEveXSP2wROghoiqkWO1drlDDZfX19b2oHdH
    vYmOkYust9o47qilQLG962Amk25xtpHN8RT8X9EUdFTtgXmDPsYK6heW5ys/CZRC
    cw1UvwZayI9yOo/h2vwJIURf5thwS/5k6gqJLmHkxAIl325juFCKhueOiQS/VlxZ
    a06lpEnDKXqxpZ1oySvmZV53mcx27dEisOyE7S4EEL/4Th6FXQKzni5ojUwJX6g/
    ix9Ox6Fa4FwbFqrV2IHbuYOudBNnZCuDJEQBSMcznx4eepTb/a/e1Gno6zV31Qpg
    3b6537XeMLmh9vOFo3Z88ignjQME7TfnykA1f0r4pWuOzsOtoad42ntoct1XNSd5
    Q1bzIpUjuA0BgIbpoTh4zHnJzfBGIxnpQKp4B26SSHPRh/iw5whviXsPBFDXcnTK
    6nt0w7l2Tsy6cxIVo+ZUlSJ/e4ey9j30+Lq6nexPn5P8eGTGzuh98it2d5OPOUv4
    xycQhD4bBVk8Ls5gCdgj2atSyHR4wnveCfIR1w8G4ooDhbfmhiL7frpZebJe6uRN
    6I2Ce6LlLB24uRJrIZ+RZR0f00WPYpApY+Q+NOShd9MZMikTWusT8NriiLvzeA0+
    CKs7HjA5q0pWQcxwEvA5wvWuU0WOt4tlGAfuAclJF29x3qDN2EBQAM+b
    -----END CERTIFICATE-----
  tls.key: |
    {{ talos_shared_gateway_com_key | indent(4) }}
